import { Inter } from 'next/font/google';
import { Footer } from '~/layouts/Footer';
import { Navigation } from '~/layouts/Navigation';
import '../styles/globals.css';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Right the Rules',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body className="grid h-screen grid-rows-[auto_1fr_auto]">
        <Navigation />
        <main className="bg-yellow-100 px-4">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
